# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U2VUjeF9309QV8WKBr6f09Xu2c2lzWo7
"""

from setuptools import setup

setup(
    name='HW1_package',
    version='0.1.0',
    description='HW1 package',
    author='Samuel Yu',
    author_email='samuel.yu@yale.edu',
    url='https://github.com/SamuelYueYu/CBB752',
    packages=['mypackage'],
)